ROBOCOPY .\upload_v2.3_no_encoded\system\library\kazshipping .\upload_v2.0-2.1.x_no_encoded\system\library\kazshipping\ * /S
ROBOCOPY .\upload_v2.3_no_encoded\admin\view\stylesheet .\upload_v2.0-2.1.x_no_encoded\admin\view\stylesheet\ * /S
ROBOCOPY .\upload_v2.3_no_encoded\admin\view\template\extension\shipping .\upload_v2.0-2.1.x_no_encoded\admin\view\template\shipping\ * /S
ROBOCOPY .upload_v2.3_no_encoded\admin\language\ru-ru\extension .\upload_v2.0-2.1.x_no_encoded\admin\language\russian\ * /S
ROBOCOPY .\upload_v2.3_no_encoded\admin\controller\extension .\upload_v2.0-2.1.x_no_encoded\admin\controller\ * /S
ROBOCOPY .\upload_v2.3_no_encoded\catalog\controller .\upload_v2.0-2.1.x_no_encoded\catalog\controller\ * /S
ROBOCOPY .\upload_v2.3_no_encoded\catalog\language\ru-ru\extension .\upload_v2.0-2.1.x_no_encoded\catalog\language\russian\ * /S
ROBOCOPY .\upload_v2.3_no_encoded\catalog\model\extension\shipping .\upload_v2.0-2.1.x_no_encoded\catalog\model\shipping\ * /S
ROBOCOPY .\upload_v2.3_no_encoded\catalog\model\localisation .\upload_v2.0-2.1.x_no_encoded\catalog\model\localisation\ * /S
